### ISSUE TITLE
Cannot read property 'responseType' of null

### ISSUE THREAD

**Issue by amrutawandakar** [danielgek/uaa-angular#1]
I i'm getting error like below, how can i resolve this
`AppComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: Cannot read property 'responseType' of null
    at OAuthService.tryLogin (angular-oauth2-oidc.js:2608)
    at new UaaService (uaa.service.ts:29)
    at _createClass (core.js:10935)
    at _createProviderInstance$1 (core.js:10907)
    at resolveNgModuleDep (core.js:10892)
    at NgModuleRef_.get (core.js:12129)
    at resolveDep (core.js:12619)
    at createClass (core.js:12481)
    at createDirectiveInstance (core.js:12326)
    at createViewNodes (core.js:13784)
View_AppComponent_Host_0 @ AppComponent_Host.ngfactory.js? [sm]:1
proxyClass @ compiler.js:14659
DebugContext_.logError @ core.js:15038
ErrorHandler.handleError @ core.js:1510
eval @ core.js:5693
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:150
NgZone.runOutsideAngular @ core.js:4708
eval @ core.js:5693
ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.js:4760
ZoneDelegate.invoke @ zone.js:390
Zone.run @ zone.js:150
eval @ zone.js:889
ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:4751
ZoneDelegate.invokeTask @ zone.js:422
Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
Promise.then (async)
scheduleMicroTask @ zone.js:584
ZoneDelegate.scheduleTask @ zone.js:413
Zone.scheduleTask @ zone.js:238
Zone.scheduleMicroTask @ zone.js:258
scheduleResolveOrReject @ zone.js:879
ZoneAwarePromise.then @ zone.js:1012
PlatformRef.bootstrapModule @ core.js:5579
eval @ main.ts:11
../../../../../src/main.ts @ main.bundle.js:60
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:75
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
AppComponent_Host.ngfactory.js? [sm]:1 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 1, nodeDef: {…}, elDef: {…}, elView: {…}}
View_AppComponent_Host_0 @ AppComponent_Host.ngfactory.js? [sm]:1
proxyClass @ compiler.js:14659
DebugContext_.logError @ core.js:15038
ErrorHandler.handleError @ core.js:1515
eval @ core.js:5693
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:150
NgZone.runOutsideAngular @ core.js:4708
eval @ core.js:5693
ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.js:4760
ZoneDelegate.invoke @ zone.js:390
Zone.run @ zone.js:150
eval @ zone.js:889
ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:4751
ZoneDelegate.invokeTask @ zone.js:422
Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
Promise.then (async)
scheduleMicroTask @ zone.js:584
ZoneDelegate.scheduleTask @ zone.js:413
Zone.scheduleTask @ zone.js:238
Zone.scheduleMicroTask @ zone.js:258
scheduleResolveOrReject @ zone.js:879
ZoneAwarePromise.then @ zone.js:1012
PlatformRef.bootstrapModule @ core.js:5579
eval @ main.ts:11
../../../../../src/main.ts @ main.bundle.js:60
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:75
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
main.ts:12 TypeError: Cannot read property 'responseType' of null
    at OAuthService.tryLogin (angular-oauth2-oidc.js:2608)
    at new UaaService (uaa.service.ts:29)
    at _createClass (core.js:10935)
    at _createProviderInstance$1 (core.js:10907)
    at resolveNgModuleDep (core.js:10892)
    at NgModuleRef_.get (core.js:12129)
    at resolveDep (core.js:12619)
    at createClass (core.js:12481)
    at createDirectiveInstance (core.js:12326)
    at createViewNodes (core.js:13784)`

**Comment by danielgek** [comment]
@amrutawandakar this is a template i made long time ago, not sure why it's not working and i don't really have time to see why... i'm sorry
